name: master

on:
  push:
    branches:
      - master
      - develop
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the mailslurper Docker image
      working-directory: mailslurper
      run: docker build . --file Dockerfile  --tag ajayy004/mailslurper:$(date +%s)
    
