name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the mailslurper Docker image
      run: docker build mailslurper/. --file mailslurper/Dockerfile  --tag ajayy004/mailslurper:$(date +%s)
